### ISSUE TITLE
static variables not resetting 

### ISSUE THREAD

**Issue by srd807** [siemenskyle/BDMT#18]
static variables not resetting after a game is played.

**Comment by dbenjaminb** [comment]
I couldn't replicate the bug, so I reset the variables on load time
https://github.com/siemenskyle/BDMT/commit/1c132370ebcd607fe7c3841693bf15f89d6fe8cc
https://github.com/siemenskyle/BDMT/commit/84db64300d90841fde649b77adc56aeb33a8ec4b
