### ISSUE TITLE
Collider not enabling ?

### ISSUE THREAD

**Issue by dbenjaminb** [siemenskyle/BDMT#27]
Can't reproduce it though.

**Comment by ghost** [comment]
pretty sure I figured out why this was happening

**Comment by dbenjaminb** [comment]
Care to enlighten us? :P

**Comment by saximaphone** [comment]
it's because you're bad at vidya gaems

**Comment by ghost** [comment]
Actually it's because Daniel is bad at video games. 
Pretty sure it was because the "last hit" thing wasn't properly getting reset on serve.

**Comment by dbenjaminb** [comment]
Oh, I see how it is. Let's all gang up on Daniel. #NERD
